[2024-08-26T10:45:26.543+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-08-26T10:45:26.580+0000] {taskinstance.py:2603} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: Spark.spark_clean manual__2024-08-26T10:45:11.503978+00:00 [queued]>
[2024-08-26T10:45:26.591+0000] {taskinstance.py:2603} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: Spark.spark_clean manual__2024-08-26T10:45:11.503978+00:00 [queued]>
[2024-08-26T10:45:26.592+0000] {taskinstance.py:2856} INFO - Starting attempt 1 of 1
[2024-08-26T10:45:26.613+0000] {taskinstance.py:2879} INFO - Executing <Task(PythonOperator): spark_clean> on 2024-08-26 10:45:11.503978+00:00
[2024-08-26T10:45:26.620+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=661) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-08-26T10:45:26.622+0000] {standard_task_runner.py:72} INFO - Started process 663 to run task
[2024-08-26T10:45:26.623+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'Spark', 'spark_clean', 'manual__2024-08-26T10:45:11.503978+00:00', '--job-id', '208', '--raw', '--subdir', 'DAGS_FOLDER/Seoul_spark.py', '--cfg-path', '/tmp/tmpj_7mi0_o']
[2024-08-26T10:45:26.625+0000] {standard_task_runner.py:105} INFO - Job 208: Subtask spark_clean
[2024-08-26T10:45:26.687+0000] {task_command.py:467} INFO - Running <TaskInstance: Spark.spark_clean manual__2024-08-26T10:45:11.503978+00:00 [running]> on host 94bdab50145e
[2024-08-26T10:45:26.795+0000] {taskinstance.py:3122} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='Spark' AIRFLOW_CTX_TASK_ID='spark_clean' AIRFLOW_CTX_EXECUTION_DATE='2024-08-26T10:45:11.503978+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-08-26T10:45:11.503978+00:00'
[2024-08-26T10:45:26.797+0000] {logging_mixin.py:190} INFO - Task instance is in running state
[2024-08-26T10:45:26.798+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2024-08-26T10:45:26.799+0000] {logging_mixin.py:190} INFO - Current task name:spark_clean state:running start_date:2024-08-26 10:45:26.580922+00:00
[2024-08-26T10:45:26.799+0000] {logging_mixin.py:190} INFO - Dag name:Spark and current dag run status:running
[2024-08-26T10:45:26.800+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-08-26T10:45:35.425+0000] {taskinstance.py:3301} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/Seoul_spark.py", line 26, in _sqlspark_data_refining
    df_pyspark = spark.read.csv(
                 ^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pyspark/sql/readwriter.py", line 740, in csv
    return self._df(self._jreader.csv(self._spark._sc._jvm.PythonUtils.toSeq(path)))
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/py4j/java_gateway.py", line 1322, in __call__
    return_value = get_return_value(
                   ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pyspark/errors/exceptions/captured.py", line 185, in deco
    raise converted from None
pyspark.errors.exceptions.captured.AnalysisException: [PATH_NOT_FOUND] Path does not exist: file:/opt/airflow/AirPollutionSeoul/Measurement_summary.csv.
[2024-08-26T10:45:35.465+0000] {logging_mixin.py:190} INFO - Task instance in failure state
[2024-08-26T10:45:35.467+0000] {logging_mixin.py:190} INFO - Task start:2024-08-26 10:45:26.580922+00:00 end:2024-08-26 10:45:35.465152+00:00 duration:8.88423
[2024-08-26T10:45:35.468+0000] {logging_mixin.py:190} INFO - Task:<Task(PythonOperator): spark_clean> dag:<DAG: Spark> dagrun:<DagRun Spark @ 2024-08-26 10:45:11.503978+00:00: manual__2024-08-26T10:45:11.503978+00:00, state:running, queued_at: 2024-08-26 10:45:11.631181+00:00. externally triggered: True>
[2024-08-26T10:45:35.477+0000] {logging_mixin.py:190} INFO - Failure caused by [PATH_NOT_FOUND] Path does not exist: file:/opt/***/AirPollutionSeoul/Measurement_summary.csv.
[2024-08-26T10:45:35.479+0000] {taskinstance.py:1225} INFO - Marking task as FAILED. dag_id=Spark, task_id=spark_clean, run_id=manual__2024-08-26T10:45:11.503978+00:00, execution_date=20240826T104511, start_date=20240826T104526, end_date=20240826T104535
[2024-08-26T10:45:35.510+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-08-26T10:45:35.511+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 208 for task spark_clean ([PATH_NOT_FOUND] Path does not exist: file:/opt/airflow/AirPollutionSeoul/Measurement_summary.csv.; 663)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 115, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 2995, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3149, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3173, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/Seoul_spark.py", line 26, in _sqlspark_data_refining
    df_pyspark = spark.read.csv(
                 ^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pyspark/sql/readwriter.py", line 740, in csv
    return self._df(self._jreader.csv(self._spark._sc._jvm.PythonUtils.toSeq(path)))
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/py4j/java_gateway.py", line 1322, in __call__
    return_value = get_return_value(
                   ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pyspark/errors/exceptions/captured.py", line 185, in deco
    raise converted from None
pyspark.errors.exceptions.captured.AnalysisException: [PATH_NOT_FOUND] Path does not exist: file:/opt/airflow/AirPollutionSeoul/Measurement_summary.csv.
[2024-08-26T10:45:35.555+0000] {local_task_job_runner.py:261} INFO - Task exited with return code 1
[2024-08-26T10:45:35.585+0000] {taskinstance.py:3891} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-08-26T10:45:35.588+0000] {local_task_job_runner.py:240} INFO - ::endgroup::
